### ISSUE TITLE
Add support in API to get all transactions (with details) pr customer pr month

### ISSUE THREAD

**Issue by runes83** [unipluss/invoicetransactions#7]

**Comment by siimav** [comment]
Find by customer's internal ID, external ID or CustomerNumber?

**Comment by runes83** [comment]
ExternalID and / or CustomerNumber.
I looked at the datamodel, if you use mvanumber (company no customer mvanumber) as partitionkey it would we simple to query by paritionkey and another property without doing an entire tablescan.

**Comment by runes83** [comment]
To be able to query the table storage for this it could be beneficiary to save the transactions with a partition/row key and tablename making the lookup easier.

**Comment by siimav** [comment]
Currently all transactions are saved with the following keys:
* Customer's internal ID + date (year-month) as Partition key
* Transaction ID (random GUID) as Row key

Using the current model, we first have to do a lookup to the Customer table to resolve either External ID or Customer number to Internal ID and then query the transaction table.

What do you suppose we should use for the table name, partition key and row key?

**Comment by runes83** [comment]
That could be sufficient, maybe cache the customer lookup table.
I'll take a another look at it when I'm back at the office.
Whats important is that it's possible to query transactions pr customer /month year without having to do a full tablescan.

**Comment by siimav** [comment]
Added in commit 5604f30d740dca162fa6c90a9b185b07c82a306a
Please see if it's what you wanted.

**Comment by runes83** [comment]
This looks good, it will avoid a tablescan to get all transactions for one customer for a given month
