### ISSUE TITLE
Top customers does not show names

### ISSUE THREAD

**Issue by runes83** [unipluss/invoicetransactions#8]
Top customers shows a guid instead of the name of the customer, it's also not clear to me what that guid is.

**Comment by siimav** [comment]
That guid you are seeing, is the internal ID of the customer. The code has a fallback that when a internal ID cannot be resolved to customer name, then it just shows the ID. Could you check that the a customer with that guid exists and has the same MVA number that you used for top customers query?

**Comment by runes83** [comment]
I will check that, and get back to you

**Comment by runes83** [comment]
I look we have mistundestood each other regarding internalRef.
I thought of internalRef as the systems reference for this transaction, for example documentid, sessionid etc. But i looks like when setting internalref it tries looking up customer with this value.

**Comment by siimav** [comment]
Yes, "InternalRef" is currently the customer's internal ID. There's a separate "ID" property for the transaction's internal ID. That ID is also used as the transaction table entity's row key.
Do you think we should do some renaming for the properties?

**Comment by runes83** [comment]
I'have added a new field ExternalRecordID witch holds the externalservice ref for the transaction.
